display_name: MBzeGuardX

icon: ./assets/images/icon.png

keywords:
  - MBzeGuardX
  - Clash
  - ClashMeta
  - Proxy

generic_name: MBzeGuardX

categories:
  - Network

startup_notify: true

include: []